### ISSUE TITLE
code

### ISSUE THREAD

**Issue by cxx-cindy** [laituan245/StackExchangeQA#1]
Hello, I want to learn the code of your paper. Can you provide it?

**Comment by laituan245** [comment]
Sorry. The work was conducted 2 years ago when I was an intern at Adobe. The code is currently in Adobe's system and I don't have access to it anymore.

**Comment by laituan245** [comment]
I will try to contact my previous internship supervisor and try to get the code. I will upload it here and let you know when I do so.
