### ISSUE TITLE
code

### ISSUE THREAD

**Issue by cxx-cindy** [laituan245/StackExchangeQA#2]
Do you have the code of this paper?Thanks

**Comment by laituan245** [comment]
No. I don't have the code.  I already mentioned the reasons here https://github.com/laituan245/StackExchangeQA/issues/1. 

Also several other methods have already achieved way better scores than our work: https://aclweb.org/aclwiki/Question_Answering_(State_of_the_art).

Maybe try this work if you are interested in getting SOTA results for answer selection: https://github.com/alexa/wqa_tanda

**Comment by cxx-cindy** [comment]
OK.
Excuse me,is there any code about some relatively new methods of attention mechanism in answer selection? I want to learn them.

**Comment by laituan245** [comment]
I am not aware of any recent paper that is specifically about attention mechanism in answer selection. I have not followed the literature recently.

For SOTA results, it seems like the popular trend is to simply try to fine-tune large BERT-based models (e.g., BERT-large or Roberta-large). Like this code: https://github.com/alexa/wqa_tanda.

In term of architectures, I found the recent Cascade Transformer to be quite interesting. It helps reduce computation time: https://github.com/alexa/wqa-cascade-transformers

**Comment by cxx-cindy** [comment]
Thanks!!!
